### PR TITLE
Added option to insert a chip when user hits space (similarly as enter).

### PR DESCRIPTION
**Pull request by koenvd**
Hi @mohbasheer,

This PR adds an option to add text to the chips from the moment the user presses space.  

It makes the UI a bit more user friendly. Like in the case of email addresses (where space is forbidden anyway) the user can continue typing email addresses and on every space an email address will be added as a new chip.

Let me know what you think.

Koen

### CODE REVIEW

**Comment by mohbasheer** [comment]
I may not check for next few days. Going for vacation I'll let you know.

Thanks Man

**Comment by mohbasheer** [comment]
I'll check and let you know.

**Comment by jeson114** [comment]
Is this gonna get merged  ?

**Comment by mohbasheer** [comment]
Sorry dude. Thanks for your effort.

I checked the code it's breaking some existing flow. Mostly I'll discard
this changes. I'll let you know the road map for the new changes if you are
interested you can contribute. But I can't do it immediately I'll be busy
with current project for next 4 weeks we can do after that. Thanks for your
time and effort.

**Pull request closed without merging**
